### ISSUE TITLE
Support org_id in neon_project

### ISSUE THREAD

**Issue by suvarnadudam** [terraform-community-providers/terraform-provider-neon#12]
Getting below error when creating project from free personal account.
"Unable to create project, got error: {"code":"","message":"modifying the suspend interval is not permitted on this account"}"

Looks like it is setting suspend interval by default. Would be great if we can remove this operation or have the ability to pass org id.

**Comment by pksunkara** [comment]
It is expected for if your neon plan doesn't support it unless you are not trying to modify the suspend interval.

**Comment by suvarnadudam** [comment]
I am not trying to modify the suspend interval. I am just trying to create a project with default settings as below.  It was working fine on my paid account but Neon has now introduced organisations feature so my paid account got converted to org account and my personal account is free. Need a way to pass org id at least to avoid this error. I am not getting this error when using other TF provider.

resource "neon_project" "example" {
  name   = "something"
  region = "aws-us-west-2"
}


Thanks

**Comment by pksunkara** [comment]
I will look into org_id, but I have another question. Did you already have a project in your personal account? I am wondering the default suspend interval I am setting is not supported for free accounts.

**Comment by suvarnadudam** [comment]
Thanks for looking into org_id. I do not have any projects in my personal account. Yes, setting the default suspend interval is not supported for free accounts.

**Comment by vadim2404** [comment]
hey, I’m representative of Neon company and can explain changes in the public API devoted organizations.

**Comment by pksunkara** [comment]
@vadim2404 Hey, can I please get access to organizations features on my neon.tech account with email pavan.sss1991@gmail.com? Thanks.

**Comment by vadim2404** [comment]
hey, I've invited you to a test org

**Comment by pksunkara** [comment]
@vadim2404 I implemented it in #14  but cannot test it because I need "Admin" access in the org (it is erroring out when I am trying to delete a created database). I am currently a member of that org.

**Comment by vadim2404** [comment]
@pksunkara , I've changed your role to admin. When will you finish, let me know – I'll revoke such permissions

**Comment by pksunkara** [comment]
I will need those permissions permanently because of the tests.

Maybe it's better if you can provide me an org instead?

**Comment by vadim2404** [comment]
Currently, we have limited number of users for whom we enabled org. This feature is in private beta. In next 2 weeks we will increase the pool of users. Then, I’ll be able to create an org for you!

**Comment by pksunkara** [comment]
@vadim2404 Okay, please let me know once done and I can release this. Thanks.

**Comment by dmiric** [comment]
This error still wasn't resolved. I'm getting the same error for free account. Is there something I can do to fix this?

**Comment by dmiric** [comment]
> hey, I’m representative of Neon company and can explain changes in the public API devoted organizations.

There are currently two plugins for neon and both are not working for free accounts at least.

**Comment by pksunkara** [comment]
@vadim2404 I had emailed 2 weeks ago. I am waiting for paid plan access to an org.

**Comment by vadim2404** [comment]
hey, you already have access to paid org - https://console.neon.tech/app/org-aged-sky-67916740/

**Comment by pksunkara** [comment]
> hey, you already have access to paid org - [console.neon.tech/app/org-aged-sky-67916740](https://console.neon.tech/app/org-aged-sky-67916740/)

I thought you would be revoking my admin permissions for that organization. But, if you plan to keep it permanently as admin, I can use that org for tests. Can you please confirm?

**Comment by vadim2404** [comment]
I want to leave it with you. but if something happens, just ping me!
