### ISSUE TITLE
Cannot create a project with PostgreSQL 16

### ISSUE THREAD

**Issue by elderfo** [terraform-community-providers/terraform-provider-neon#7]
Per Neon's API documentation, PostgreSQL 16 is supported. https://api-docs.neon.tech/reference/createproject

Can this value be added?

**Comment by w7it** [comment]
@elderfo as temporary workaround you are able to create project with PostgreSQL 16 version manually from web-interface or api and then import it to terraform:
```sh
terraform import neon_project.main <project_id>
```

and don't forget to use `ignore_changes` to prevent updating:
```tf
resource "neon_project" "main" {
  name      = "example"
  region_id = "aws-us-east-1"

  lifecycle {
    ignore_changes = [ pg_version ]
  }
}
```
