### ISSUE TITLE
Error: Provider produced inconsistent result after apply (`was cty.StringVal("k8s-pod"), but now cty.StringVal("k8s-neonvm")`)

### ISSUE THREAD

**Issue by SvanteRichter** [terraform-community-providers/terraform-provider-neon#9]
Hello!

Thank you for this provider!
Some time during the last week I have started getting the following error. My last successful run seems to have been on the 19:th and today I get the error. 

```
Error: Provider produced inconsistent result after apply

When applying changes to neon_branch.main, provider
"provider[\"registry.opentofu.org/terraform-community-providers/neon\"]"
produced an unexpected new value: .endpoint.compute_provisioner: was
cty.StringVal("k8s-pod"), but now cty.StringVal("k8s-neonvm").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Do you have any tips for how I can fix it?

Thanks!

**Comment by pksunkara** [comment]
Please give me more details if you did any of the following:

1. Did you change your neon plan?
2. Did you change the terraform resource?

**Comment by SvanteRichter** [comment]
The neon project was existing, and was setup with a separate terraform repo, in this run I create a new branch by running

```
resource "neon_branch" "main" {
  name       = terraform.workspace
  parent_id  = data.aws_ssm_parameter.neon_init_branch_id.value
  project_id = data.aws_ssm_parameter.neon_project_id.value
  endpoint = {
    suspend_timeout = 60
  }
}
```

Where those parent_id & project_id parameters where created in the initial setup of the project.

I now tried to setup a completely new project, from scratch, and I get similar errors:

```
Error: Provider produced inconsistent result after apply
When applying changes to neon_project.main, provider
"provider[\"registry.terraform.io/terraform-community-providers/neon\"]"
produced an unexpected new value: .branch.endpoint.compute_provisioner: was
cty.StringVal("k8s-pod"), but now cty.StringVal("k8s-neonvm").
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

The relevant terraform code seems to be:

```
resource "neon_project" "main" {
  region_id = "aws-${var.region}"
  name      = var.project_name
  branch = {
    name = "_init"
    endpoint = {
      suspend_timeout = 60
    }
  }
}
```

Where `project_name` was "neon-new-api-test" and `region` was "eu-central-1".

Please let me know if I can help in any way or if you have a pointer for what to look at if you don't have the time to look at it! thanks!

**Comment by SvanteRichter** [comment]
Thank you so much for the very fast fix!

**Comment by pksunkara** [comment]
Np. I am not sure how much I can support going forward though.

Neon changed their plans and the free plan doesn't support some of the features from the provider anymore. That means I can't meaningfully test everything.

I did ask Neon support for a free upgrade to Launch plan for the account that I run terraform tests. But looks like they don't care.

It this situation continues, I will stop maintaining this provider and archive it. And also probably move my projects away from Neon because I don't plan to use any infra that doesn't support terraform or other IaC.

**Comment by SvanteRichter** [comment]
I pinged the person I've talked to at neon about this, hopefully they can give you a launch plan. If not I can maybe get my company to sponsor it, and if not I'd be happy to pay the 19$/month for it personally.

I think neon should help you out with this but if the blocker for you to continue development is getting a paid launch plan I'll help out however I can.

This provider has really been helpful for me and your quick help on this issue was great!

**Comment by pksunkara** [comment]
> If not I can maybe get my company to sponsor it, and if not I'd be happy to pay the 19$/month for it personally.

I don't think I would be able to accept this. It's more of a principle.

I think Neon should care about their customers enough to either provide a terraform provider themselves or support someone who wants to by giving them full access.

**Comment by acervantes23** [comment]
Hi @SahAssar can you email me at atli@neon.tech to discuss how we can best support you?

**Comment by acervantes23** [comment]
Hi @pksunkara I sent you an email! My sincerest apologies for the delayed response from our team.
